include:
  # lynx aka urchin
  - board: nice_nano_v2
    shield: lynx_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: lynx_right nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart

  - board: nice_nano_v2
    shield: settings_reset
