include:
  # lynx aka urchin
  - board: nice_nano_v2
    shield: lynx_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: lynx_right nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart

  # calypso aka corne
  - board: nice_nano_v2
    shield: calypso_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: calypso_right
    snippet: studio-rpc-usb-uart

  # Helios aka kinesis adv2
  - board: blackpill_f411ce
    shield: helios

  - board: nice_nano_v2
    shield: settings_reset
