draw_config:
  dark_mode: auto

parse_config:
  mark_alternate_layer_activators: true
  tap_toggle_label: tap-toggle
  trans_legend:
    t: $$mdi:transfer$$
    type: trans

  raw_binding_map:
    # Modifiers
    "&caps_word": $$mdi:alpha-w-box$$
    "&swapper": $$mdi:swap-horizontal$$

    # Bluetooth
    "&bt BT_SEL 0":
      tap: $$mdi:bluetooth-connect$$
      hold: 1
    "&bt BT_SEL 1":
      tap: $$mdi:bluetooth-connect$$
      hold: 2
    "&bt BT_SEL 2":
      tap: $$mdi:bluetooth-connect$$
      hold: 3
    "&bt BT_SEL 3":
      tap: $$mdi:bluetooth-connect$$
      hold: 4
    "&bt BT_SEL 4":
      tap: $$mdi:bluetooth-connect$$
      hold: 5
    "&bt BT_CLR":
      tap: $$mdi:bluetooth-off$$

    # Reset
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
    "&bootloader":
      tap: $$mdi:progress-download$$

  zmk_keycode_map:
    AMPERSAND: '&'
    AMPS: '&'
    APOS: ''''
    APOSTROPHE: ''''
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    BSPC: $$mdi:backspace$$
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    ENTER: "$$mdi:keyboard-return$$"
    EQUAL: '='
    ESC: '$$mdi:keyboard-esc$$'
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    K_CANCEL: $$mdi:cancel$$
    LALT: $$mdi:apple-keyboard-option$$
    LBKT: '['
    LBRC: '{'
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LGUI: $$mdi:apple-keyboard-command$$
    LPAR: (
    LSHFT: $$mdi:apple-keyboard-shift$$
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE2: '|'
    PIPE: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RALT: $$mdi:apple-keyboard-option$$
    RBKT: ']'
    RBRC: '}'
    RCTRL: $$mdi:apple-keyboard-control$$
    RETURN: "$$mdi:keyboard-return$$"
    RGUI: $$mdi:apple-keyboard-command$$
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    RSHFT: $$mdi:apple-keyboard-shift$$
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SPACE: "$$mdi:keyboard-space$$"
    SQT: ''''
    STAR: '*'
    TAB: $$mdi:keyboard-tab$$
    TILDE2: '~'
    TILDE: '~'
    UNDER: _
    UNDERSCORE: _
