on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - build.yaml

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  # credits: BerkeleyTrue/zmk-keyboards
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: set now
        run: echo "NOW=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware

      - name: Publish release
        uses: svenstaro/upload-release-action@v2
        with:
          file: firmware/*.uf2
          file_glob: true
          tag: ${{ env.NOW }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  draw:
    needs: build
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap_drawer.config.yaml"
      output_folder: assets
      install_branch: main
      parse_args: "lynx:'-c 10 -z config/lynx.keymap' calypso:'-c 10 -z config/calypso.keymap'"
      draw_args: "lynx:'-k ferris/sweep -l LAYOUT_split_3x5_2' calypso:'-k corne_rotated -l LAYOUT_split_3x5_3'"
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
