name: Build ZMK Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - main # Trigger on commits to main
    tags:
      - "*" # Trigger on tag pushes

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  # credits: BerkeleyTrue/zmk-keyboards
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Get Current Datetime
        id: datetime
        run: echo "datetime=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware ${{ env.datetime }}
          path: firmware ${{ env.datetime }}
