name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap_drawer.config.yaml"
      output_folder: assets
      amend_commit: true
      parse_args: >-
        lynx:'-c 10 -z config/lynx.keymap'
        calypso:'-c 10 -z config/calypso.keymap'
        helios:'-z config/helios.keymap'
      draw_args:
        lynx:'-k ferris/sweep -l LAYOUT_split_3x5_2'
        calypso:'-k splitkb/aurora/corne -l LAYOUT_split_3x5_3'
        helios:'-k kinesis/stapelberg -l LAYOUT'
