name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      install_branch: "main"
      keymap_patterns: "config/*.keymap"
      config_path: "keymap_drawer.config.yaml"
      output_folder: "assets"
      # parse_args: "lynx:'-c 10 -z config/boards/shields/lynx/lynx.keymap'"
      # draw_args: "lynx:'-k ferris/sweep -l LAYOUT_split_3x5_2'"
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
